name: Feature Request
description: Suggest an idea or enhancement for ApraLinuxUtils
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make ApraLinuxUtils better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like ApraLinuxUtils to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - GPIO
        - I2C
        - PWM
        - USB Storage
        - Threading
        - Error Handling
        - Documentation
        - Build System
        - New Hardware Interface
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my project
        - High - Very important
        - Medium - Would be nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        In my project, I need to...
        This feature would allow me to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example API / Usage
      description: If applicable, show how you envision using this feature
      placeholder: |
        ```cpp
        // Example usage
        apra::NewFeature feature;
        feature.doSomething();
        ```
      render: cpp
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: "This could be implemented by..."
    validations:
      required: false

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change to existing APIs?
      options:
        - "No - Backward compatible"
        - "Yes - Breaking change required"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: similar
    attributes:
      label: Similar Features in Other Libraries
      description: Have you seen similar features in other libraries?
      placeholder: "Library X has a similar feature that..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, diagrams, or screenshots
      placeholder: "Additional information..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues/PRs to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals (embedded Linux utilities)
          required: true
